# Single source of truth for the version string is version.txt.
# `make update-version` propagates it to the manifest and to version.js, which every module
# imports. Run it after editing version.txt, then commit the result.

VERSION := $(shell cat version.txt)

update-version:
	@echo "Updating version to $(VERSION)"
	@sed -i '' "s/\"version\": \".*\"/\"version\": \"$(VERSION)\"/" manifest.json
	@printf "// Central version stamp for PRO extension.\n// Generated by 'make update-version' from version.txt — do not edit by hand.\nexport const PRO_VERSION = '%s';\n" "$(VERSION)" > version.js

# Verify manifest.json and version.js agree with version.txt.
check-version:
	@grep -q "\"version\": \"$(VERSION)\"" manifest.json || { echo "manifest.json is not at $(VERSION)"; exit 1; }
	@grep -q "PRO_VERSION = '$(VERSION)'" version.js   || { echo "version.js is not at $(VERSION)"; exit 1; }
	@echo "version $(VERSION) is consistent"

.PHONY: update-version check-version

# --- packaging -------------------------------------------------------------
# Builds a zip containing only what the extension needs to run: the manifest,
# version.js and src/. Test pages, the Makefile and repo metadata are excluded.
#
#   make package        -> pivotal-route-overlay-$(VERSION).zip, wrapped in a
#                          folder, ready to unzip and "Load unpacked"
#   make package-store  -> pivotal-route-overlay-$(VERSION)-store.zip, with
#                          manifest.json at the root, for Web Store upload

NAME    := pivotal-route-overlay
STAGE   := build/$(NAME)
SHIP    := manifest.json version.js src LICENSE README

package: check-version
	@rm -rf build "$(NAME)-$(VERSION).zip"
	@mkdir -p $(STAGE)
	@for f in $(SHIP); do cp -R "$$f" $(STAGE)/; done
	@find build -name '.DS_Store' -delete
	@cd build && zip -qr "../$(NAME)-$(VERSION).zip" $(NAME)
	@rm -rf build
	@echo "built $(NAME)-$(VERSION).zip"

package-store: check-version
	@rm -rf build "$(NAME)-$(VERSION)-store.zip"
	@mkdir -p build/root
	@for f in $(SHIP); do cp -R "$$f" build/root/; done
	@find build -name '.DS_Store' -delete
	@cd build/root && zip -qr "../../$(NAME)-$(VERSION)-store.zip" .
	@rm -rf build
	@echo "built $(NAME)-$(VERSION)-store.zip"

.PHONY: package package-store
