# Single source of truth for the version string is version.txt.
# `make update-version` propagates it to the manifest and to version.js, which every module
# imports. Run it after editing version.txt, then commit the result.

VERSION := $(shell cat version.txt)

update-version:
	@echo "Updating version to $(VERSION)"
	@sed -i '' "s/\"version\": \".*\"/\"version\": \"$(VERSION)\"/" manifest.json
	@printf "// Central version stamp for PRO extension.\n// Generated by 'make update-version' from version.txt — do not edit by hand.\nexport const PRO_VERSION = '%s';\n" "$(VERSION)" > version.js

# Verify manifest.json and version.js agree with version.txt.
check-version:
	@grep -q "\"version\": \"$(VERSION)\"" manifest.json || { echo "manifest.json is not at $(VERSION)"; exit 1; }
	@grep -q "PRO_VERSION = '$(VERSION)'" version.js   || { echo "version.js is not at $(VERSION)"; exit 1; }
	@echo "version $(VERSION) is consistent"

.PHONY: update-version check-version
